### ISSUE TITLE
Just a graphical menu

### ISSUE THREAD

**Issue by DataPools** [Fabricio20/HubBasics#73]
Hello,
I'd like a graphical menu to be added to the inventory on join. However, in order to do this I must turn on JoinItems. I do not want my players to receive any items except for the menu one. However, the plugin does not work without at least one item define as a Join item.

**Comment by Fabricio20** [comment]
As far as I remember you are supposed to use the JoinItems feature to give the player the menu item.

**Comment by DataPools** [comment]
It seems that they are separate. If I define a compass to be given by JoinItems then it will give a compass and the graphical menu item.

**Comment by MrRiptide** [comment]
You can create a graphical menu option in the config(Near the bottom, underneath the join items), and then set "AddToInventory" to true, and customize your menu from there.  Otherwise, if you want the menu also accessable via a command, you can use a plugin that allows for graphical menus, such as ChestCommands or BossShop, and the configure the JoinItems to open the graphical menu via command on rightclick.

Hope this helps. =D
